import { Component, signal } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { MapComponent } from './map.component/map.component';

import { Marker } from './core/models/Marker.interface';

@Component({
  selector: 'app-root',
  
  imports: [RouterOutlet,MapComponent],
  templateUrl: './app.html',
  styleUrl: './app.scss'
})
export class App {
  protected readonly title = signal('leaf');

markersArray: Marker[] = [
  { id: '1', name: 'Mohammed Benali', lat: 33.5731, lng: -7.5898, country: 'Morocco', label: 'Client', addr_city: 'Casablanca', addr_street: '123 Avenue Mohammed V' },
  { id: '2', name: 'Klaus Mueller GmbH', country: 'Germany', label: 'Supplier', addr_city: 'Munich', addr_province: 'Bavaria', addr_street: 'Bayerstraße 45' },
  { id: '3', name: 'Fatima Zahra Trading', lat: 34.0209, lng: -6.8416, country: 'Morocco', label: 'Client', addr_city: 'Rabat', addr_street: 'Rue Ibn Batouta 12' },
  { id: '4', name: 'Bayerische Maschinen', country: 'Germany', label: 'Supplier', addr_city: 'Stuttgart', addr_province: 'Baden-Württemberg', addr_street: 'Industriestraße 89' },
  { id: '5', name: 'Ahmed El Mansouri', lat: 31.6340, lng: -7.9999, country: 'Morocco', label: 'Client', addr_city: 'Marrakech', addr_street: 'Jemaa el-Fnaa 56' },
  { id: '6', name: 'Hansa Textiles AG', country: 'Germany', label: 'Supplier', addr_city: 'Hamburg', addr_street: 'Hafenstraße 234' },
  { id: '7', name: 'Youssef Chraibi', lat: 34.0331, lng: -5.0003, country: 'Morocco', label: 'Client', addr_city: 'Fes', addr_street: 'Rue Talaa 78' },
  { id: '8', name: 'Bavarian Electronics', country: 'Germany', label: 'Supplier', addr_city: 'Nuremberg', addr_province: 'Bavaria', addr_street: 'Elektronikallee 12' },
  { id: '9', name: 'Amina El Fassi', lat: 34.0171, lng: -6.8345, country: 'Morocco', label: 'Client', addr_city: 'Salé', addr_street: 'Avenue Hassan II 34' },
  { id: '10', name: 'Deutsche Chemie GmbH', country: 'Germany', label: 'Supplier', addr_city: 'Cologne', addr_province: 'North Rhine-Westphalia', addr_street: 'Chemieweg 67' },
  { id: '11', name: 'Karim Ouazzani', lat: 35.7673, lng: -5.8003, country: 'Morocco', label: 'Client', addr_city: 'Tangier', addr_street: 'Boulevard Pasteur 89' },
  { id: '12', name: 'Ruhr Valley Steel', country: 'Germany', label: 'Supplier', addr_city: 'Essen', addr_province: 'North Rhine-Westphalia', addr_street: 'Stahlstraße 156' },
  { id: '13', name: 'Nadia Amrani', lat: 30.4202, lng: -9.5981, country: 'Morocco', label: 'Client', addr_city: 'Agadir', addr_street: 'Avenue du Soleil 23' },
  { id: '14', name: 'Saxon Precision Tools', country: 'Germany', label: 'Supplier', addr_city: 'Dresden', addr_province: 'Saxony', addr_street: 'Werkzeugstraße 45' },
  { id: '15', name: 'Hassan El Khadir', lat: 35.1703, lng: -2.9394, country: 'Morocco', label: 'Client', addr_city: 'Nador', addr_street: 'Rue Mohammed V 67' },
  { id: '16', name: 'Franconian Wood Products', country: 'Germany', label: 'Supplier', addr_city: 'Würzburg', addr_province: 'Bavaria', addr_street: 'Forststraße 78' },
  { id: '17', name: 'Samira Alaoui', lat: 32.2998, lng: -9.2371, country: 'Morocco', label: 'Client', addr_city: 'Essaouira', addr_street: 'Rue de la Corniche 45' },
  { id: '18', name: 'Hannoverian Machinery', country: 'Germany', label: 'Supplier', addr_city: 'Hanover', addr_province: 'Lower Saxony', addr_street: 'Maschinenweg 34' },
  { id: '19', name: 'Mustapha Jilali', lat: 35.2629, lng: -6.5688, country: 'Morocco', label: 'Client', addr_city: 'Tetouan', addr_street: 'Avenue Mohammed VI 12' },
  { id: '20', name: 'Black Forest Timber', country: 'Germany', label: 'Supplier', addr_city: 'Freiburg', addr_province: 'Baden-Württemberg', addr_street: 'Waldweg 89' },
  { id: '21', name: 'Khadija El Idrissi', lat: 31.9342, lng: -4.4403, country: 'Morocco', label: 'Client', addr_city: 'Errachidia', addr_street: 'Rue Principale 56' },
  { id: '22', name: 'Bremen Shipping Co', country: 'Germany', label: 'Supplier', addr_city: 'Bremen', addr_street: 'Hafenplatz 23' },
  { id: '23', name: 'Omar Belghiti', lat: 35.7847, lng: -5.8129, country: 'Morocco', label: 'Client', addr_city: 'Tangier', addr_street: 'Rue de France 78' },
  { id: '24', name: 'Thuringian Glassworks', country: 'Germany', label: 'Supplier', addr_city: 'Weimar', addr_province: 'Thuringia', addr_street: 'Glasstraße 45' },
  { id: '25', name: 'Leila Bennis', lat: 32.3331, lng: -6.3999, country: 'Morocco', label: 'Client', addr_city: 'Beni Mellal', addr_street: 'Avenue Hassan I 34' },
  { id: '26', name: 'Pfalz Wine Suppliers', country: 'Germany', label: 'Supplier', addr_city: 'Mainz', addr_province: 'Rhineland-Palatinate', addr_street: 'Weinstraße 67' },
  { id: '27', name: 'Rachid Laaroussi', lat: 34.6845, lng: -1.9098, country: 'Morocco', label: 'Client', addr_city: 'Oujda', addr_street: 'Boulevard Mohammed V 89' },
  { id: '28', name: 'Mecklenburg Dairy', country: 'Germany', label: 'Supplier', addr_city: 'Schwerin', addr_province: 'Mecklenburg-Vorpommern', addr_street: 'Milchstraße 12' },
  { id: '29', name: 'Zineb Kabbaj', lat: 34.2610, lng: -6.5802, country: 'Morocco', label: 'Client', addr_city: 'Kenitra', addr_street: 'Rue Ibn Sina 56' },
  { id: '30', name: 'Saarland Steel Mills', country: 'Germany', label: 'Supplier', addr_city: 'Saarbrücken', addr_province: 'Saarland', addr_street: 'Stahlwerkstraße 78' },
  { id: '31', name: 'Abdelatif Choukri', lat: 30.3256, lng: -9.4871, country: 'Morocco', label: 'Client', addr_city: 'Taroudant', addr_street: 'Avenue des Palmiers 23' },
  { id: '32', name: 'Brandenburg Agricultural', country: 'Germany', label: 'Supplier', addr_city: 'Potsdam', addr_province: 'Brandenburg', addr_street: 'Feldweg 45' },
  { id: '33', name: 'Imane Rifi', lat: 35.1689, lng: -2.9394, country: 'Morocco', label: 'Client', addr_city: 'Al Hoceima', addr_street: 'Rue du Port 67' },
  { id: '34', name: 'Bavarian Brewery', country: 'Germany', label: 'Supplier', addr_city: 'Munich', addr_province: 'Bavaria', addr_street: 'Bierstraße 89' },
  { id: '35', name: 'Rashid El Malki', lat: 33.8933, lng: -6.3333, country: 'Morocco', label: 'Client', addr_city: 'Khouribga', addr_street: 'Avenue Mohammed VI 34' },
  { id: '36', name: 'Hessian Automotive', country: 'Germany', label: 'Supplier', addr_city: 'Frankfurt', addr_province: 'Hesse', addr_street: 'Autobahnstraße 156' },
  { id: '37', name: 'Asmaa El Ouahabi', lat: 34.3000, lng: -2.1667, country: 'Morocco', label: 'Client', addr_city: 'Chefchaouen', addr_street: 'Rue des Cascades 78' },
  { id: '38', name: 'Lower Saxony Plastics', country: 'Germany', label: 'Supplier', addr_city: 'Braunschweig', addr_province: 'Lower Saxony', addr_street: 'Kunststoffweg 23' },
  { id: '39', name: 'Mehdi Berrada', lat: 33.2500, lng: -8.5000, country: 'Morocco', label: 'Client', addr_city: 'Safi', addr_street: 'Port Avenue 45' },
  { id: '40', name: 'Rhineland Chemicals', country: 'Germany', label: 'Supplier', addr_city: 'Düsseldorf', addr_province: 'North Rhine-Westphalia', addr_street: 'Chemikalienstraße 67' },
  { id: '41', name: 'Nawal El Hariri', lat: 34.2333, lng: -4.0000, country: 'Morocco', label: 'Client', addr_city: 'Khenifra', addr_street: 'Rue Principale 89' },
  { id: '42', name: 'Bavarian Ceramics', country: 'Germany', label: 'Supplier', addr_city: 'Regensburg', addr_province: 'Bavaria', addr_street: 'Keramikstraße 12' },
  { id: '43', name: 'Yassine Fassi', lat: 35.1667, lng: -2.9333, country: 'Morocco', label: 'Client', addr_city: 'Martil', addr_street: 'Avenue de la Mer 56' },
  { id: '44', name: 'Saxon Motors', country: 'Germany', label: 'Supplier', addr_city: 'Leipzig', addr_province: 'Saxony', addr_street: 'Motorenstraße 78' },
  { id: '45', name: 'Khouloud Cherkaoui', lat: 33.9733, lng: -6.7333, country: 'Morocco', label: 'Client', addr_city: 'Mohammedia', addr_street: 'Boulevard Royal 34' },
  { id: '46', name: 'Baden-Württemberg Electronics', country: 'Germany', label: 'Supplier', addr_city: 'Mannheim', addr_province: 'Baden-Württemberg', addr_street: 'Elektronikplatz 45' },
  { id: '47', name: 'Hicham El Ghorfi', lat: 32.5833, lng: -7.5833, country: 'Morocco', label: 'Client', addr_city: 'El Jadida', addr_street: 'Port Street 67' },
  { id: '48', name: 'Franconian Glass', country: 'Germany', label: 'Supplier', addr_city: 'Bamberg', addr_province: 'Bavaria', addr_street: 'Glasallee 89' },
  { id: '49', name: 'Souad El Mokhtari', lat: 34.6833, lng: -1.9000, country: 'Morocco', label: 'Client', addr_city: 'Berkane', addr_street: 'Rue Mohammed V 23' },
  { id: '50', name: 'Thuringia Textiles', country: 'Germany', label: 'Supplier', addr_city: 'Erfurt', addr_province: 'Thuringia', addr_street: 'Textilstraße 156' },
  { id: '51', name: 'Driss El Kabbouri', lat: 33.8303, lng: -4.8500, country: 'Morocco', label: 'Client', addr_city: 'Azrou', addr_street: 'Avenue des Cedres 78' },
  { id: '52', name: 'Hamburg Maritime', country: 'Germany', label: 'Supplier', addr_city: 'Hamburg', addr_street: 'Seestraße 34' },
  { id: '53', name: 'Latifa Amrani', lat: 31.5125, lng: -9.7700, country: 'Morocco', label: 'Client', addr_city: 'Tiznit', addr_street: 'Rue du Commerce 45' },
  { id: '54', name: 'Bavarian Food Processing', country: 'Germany', label: 'Supplier', addr_city: 'Augsburg', addr_province: 'Bavaria', addr_street: 'Lebensmittelstraße 67' },
  { id: '55', name: 'Karim El Fassi', lat: 34.2500, lng: -6.5833, country: 'Morocco', label: 'Client', addr_city: 'Sidi Kacem', addr_street: 'Avenue Hassan II 89' },
  { id: '56', name: 'North Rhine Construction', country: 'Germany', label: 'Supplier', addr_city: 'Duisburg', addr_province: 'North Rhine-Westphalia', addr_street: 'Baustelle 12' },
  { id: '57', name: 'Hanae Tazi', lat: 33.9000, lng: -6.8833, country: 'Morocco', label: 'Client', addr_city: 'Bouskoura', addr_street: 'Rue des Orangers 56' },
  { id: '58', name: 'Saxony Mining', country: 'Germany', label: 'Supplier', addr_city: 'Chemnitz', addr_province: 'Saxony', addr_street: 'Bergbaustraße 78' },
  { id: '59', name: 'Oussama El Khayat', lat: 35.5667, lng: -5.3667, country: 'Morocco', label: 'Client', addr_city: 'Fnideq', addr_street: 'Rue de la Plage 34' },
  { id: '60', name: 'Bavarian Pharmaceuticals', country: 'Germany', label: 'Supplier', addr_city: 'Würzburg', addr_province: 'Bavaria', addr_street: 'Medikamentenstraße 45' },
  { id: '61', name: 'Samira El Mansouri', lat: 32.6833, lng: -8.3833, country: 'Morocco', label: 'Client', addr_city: 'Taroudannt', addr_street: 'Avenue des Roses 67' },
  { id: '62', name: 'Hesse Engineering', country: 'Germany', label: 'Supplier', addr_city: 'Wiesbaden', addr_province: 'Hesse', addr_street: 'Ingenieurstraße 89' },
  { id: '63', name: 'Mostafa Choukri', lat: 35.2333, lng: -4.6667, country: 'Morocco', label: 'Client', addr_city: 'Taourirt', addr_street: 'Rue Principale 23' },
  { id: '64', name: 'Baden Automotive Parts', country: 'Germany', label: 'Supplier', addr_city: 'Karlsruhe', addr_province: 'Baden-Württemberg', addr_street: 'Autoteilestraße 156' },
  { id: '65', name: 'Naima El Alaoui', lat: 31.6333, lng: -8.0000, country: 'Morocco', label: 'Client', addr_city: 'Marrakech', addr_street: 'Rue de la Palmeraie 78' },
  { id: '66', name: 'Lower Saxony Forestry', country: 'Germany', label: 'Supplier', addr_city: 'Oldenburg', addr_province: 'Lower Saxony', addr_street: 'Forstweg 12' },
  { id: '67', name: 'Youssef El Idrissi', lat: 35.1667, lng: -2.9333, country: 'Morocco', label: 'Client', addr_city: 'Al Hoceima', addr_street: 'Port Street 56' },
  { id: '68', name: 'Bavarian Metal Works', country: 'Germany', label: 'Supplier', addr_city: 'Ingolstadt', addr_province: 'Bavaria', addr_street: 'Metallstraße 78' },
  { id: '69', name: 'Khadija El Amrani', lat: 33.5500, lng: -7.6333, country: 'Morocco', label: 'Client', addr_city: 'Casablanca', addr_street: 'Rue de la Liberté 34' },
  { id: '70', name: 'North Rhine Electronics', country: 'Germany', label: 'Supplier', addr_city: 'Mönchengladbach', addr_province: 'North Rhine-Westphalia', addr_street: 'Elektronikallee 45' },
  { id: '71', name: 'Rachid Ouazzani', lat: 34.0333, lng: -5.0000, country: 'Morocco', label: 'Client', addr_city: 'Fes', addr_street: 'Rue Talaa Kbira 67' },
  { id: '72', name: 'Thuringia Machinery', country: 'Germany', label: 'Supplier', addr_city: 'Gera', addr_province: 'Thuringia', addr_street: 'Maschinenstraße 89' },
  { id: '73', name: 'Fatima El Khadir', lat: 35.7667, lng: -5.8000, country: 'Morocco', label: 'Client', addr_city: 'Tangier', addr_street: 'Boulevard du 9 Avril 23' },
  { id: '74', name: 'Franconian Construction', country: 'Germany', label: 'Supplier', addr_city: 'Bayreuth', addr_province: 'Bavaria', addr_street: 'Baumaterialstraße 156' },
  { id: '75', name: 'Abdelatif Jilali', lat: 35.2667, lng: -6.5667, country: 'Morocco', label: 'Client', addr_city: 'Tetouan', addr_street: 'Rue de l\'Industrie 78' },
  { id: '76', name: 'Saxony Chemicals', country: 'Germany', label: 'Supplier', addr_city: 'Dresden', addr_province: 'Saxony', addr_street: 'Chemikalienweg 12' },
  { id: '77', name: 'Samira Belghiti', lat: 34.6833, lng: -1.9000, country: 'Morocco', label: 'Client', addr_city: 'Oujda', addr_street: 'Avenue Mohammed VI 56' },
  { id: '78', name: 'Bavarian Food Products', country: 'Germany', label: 'Supplier', addr_city: 'Passau', addr_province: 'Bavaria', addr_street: 'Lebensmittelallee 78' },
  { id: '79', name: 'Hassan Laaroussi', lat: 35.1667, lng: -2.9333, country: 'Morocco', label: 'Client', addr_city: 'Nador', addr_street: 'Rue Mohammed V 34' },
  { id: '80', name: 'Hesse Textiles', country: 'Germany', label: 'Supplier', addr_city: 'Kassel', addr_province: 'Hesse', addr_street: 'Textilallee 45' },
  { id: '81', name: 'Amina Choukri', lat: 33.9333, lng: -5.0000, country: 'Morocco', label: 'Client', addr_city: 'Sefrou', addr_street: 'Rue Principale 67' },
  { id: '82', name: 'Lower Saxony Chemicals', country: 'Germany', label: 'Supplier', addr_city: 'Osnabrück', addr_province: 'Lower Saxony', addr_street: 'Chemieweg 89' },
  { id: '83', name: 'Karim El Fassi', lat: 32.3333, lng: -6.3667, country: 'Morocco', label: 'Client', addr_city: 'Beni Mellal', addr_street: 'Avenue Hassan II 23' },
  { id: '84', name: 'Baden-Württemberg Machinery', country: 'Germany', label: 'Supplier', addr_city: 'Stuttgart', addr_province: 'Baden-Württemberg', addr_street: 'Maschinenstraße 156' },
  { id: '85', name: 'Nadia Ouazzani', lat: 34.2333, lng: -6.3500, country: 'Morocco', label: 'Client', addr_city: 'Sidi Ifni', addr_street: 'Rue du Port 78' },
  { id: '86', name: 'Bavarian Wood Industries', country: 'Germany', label: 'Supplier', addr_city: 'Rosenheim', addr_province: 'Bavaria', addr_street: 'Forststraße 12' },
  { id: '87', name: 'Mohammed El Idrissi', lat: 35.1667, lng: -2.9333, country: 'Morocco', label: 'Client', addr_city: 'Al Hoceima', addr_street: 'Avenue de la Mer 56' },
  { id: '88', name: 'North Rhine Automotive', country: 'Germany', label: 'Supplier', addr_city: 'Wuppertal', addr_province: 'North Rhine-Westphalia', addr_street: 'Autobahnallee 78' },
  { id: '89', name: 'Fatima El Mansouri', lat: 31.6333, lng: -7.9833, country: 'Morocco', label: 'Client', addr_city: 'Marrakech', addr_street: 'Jemaa el-Fnaa 34' },
  { id: '90', name: 'Thuringia Food Processing', country: 'Germany', label: 'Supplier', addr_city: 'Jena', addr_province: 'Thuringia', addr_street: 'Lebensmittelstraße 45' },
  { id: '91', name: 'Youssef El Khadir', lat: 33.8333, lng: -5.5500, country: 'Morocco', label: 'Client', addr_city: 'Azilal', addr_street: 'Rue Principale 67' },
  { id: '92', name: 'Franconian Electronics', country: 'Germany', label: 'Supplier', addr_city: 'Erlangen', addr_province: 'Bavaria', addr_street: 'Elektronikstraße 89' },
  { id: '93', name: 'Samira Jilali', lat: 35.2667, lng: -6.5667, country: 'Morocco', label: 'Client', addr_city: 'Tetouan', addr_street: 'Boulevard Mohammed V 23' },
  { id: '94', name: 'Bavarian Construction', country: 'Germany', label: 'Supplier', addr_city: 'Landshut', addr_province: 'Bavaria', addr_street: 'Baustellenstraße 156' },
  { id: '95', name: 'Hassan Belghiti', lat: 34.6833, lng: -1.9000, country: 'Morocco', label: 'Client', addr_city: 'Oujda', addr_street: 'Rue de l\'Industrie 78' },
  { id: '96', name: 'Hesse Chemicals', country: 'Germany', label: 'Supplier', addr_city: 'Marburg', addr_province: 'Hesse', addr_street: 'Chemikalienallee 12' },
  { id: '97', name: 'Amina Laaroussi', lat: 35.1667, lng: -2.9333, country: 'Morocco', label: 'Client', addr_city: 'Nador', addr_street: 'Avenue Hassan II 56' },
  { id: '98', name: 'Karim Choukri', country: 'Germany', label: 'Supplier', addr_city: 'Magdeburg', addr_province: 'Saxony-Anhalt', addr_street: 'Industriestraße 78' },
  { id: '99', name: 'Nadia El Fassi', lat: 32.3333, lng: -6.3667, country: 'Morocco', label: 'Client', addr_city: 'Beni Mellal', addr_street: 'Rue Mohammed VI 34' },
  { id: '100', name: 'Mohammed Ouazzani', country: 'Germany', label: 'Supplier', addr_city: 'Kiel', addr_province: 'Schleswig-Holstein', addr_street: 'Hafenstraße 45' }
];



}
